### ISSUE TITLE
建议把配置的预处理或者mixin部分增加一下，加个弹窗下载配置也可以。

### ISSUE THREAD

**Issue by MetaCubeX** [yaling888/SoulX#1]
首先大佬的项目越来越多了，试用了一下提些意见。
另外这个图标是不是可以换一换，有点暴力了。

题外话：win-tun的clash分支，内网 socks 的 udp 收发貌似有问题。 还有公网访问不了内网设备

**Comment by MetaCubeX** [comment]
还有勾选判断，开启了就关不了。

**Comment by MetaCubeX** [comment]
大佬。。你理理我嘛

**Comment by yaling888** [comment]
此项目的目标是实现一个像linux systemd和macOS launchctl plist一样可以在后台运行的服务，并不关心内核配置文件方面的问题，有多个配置文件需要切换时可以把文件名改为`config.yaml`再重载配置。

**Comment by yaling888** [comment]
> 首先大佬的项目越来越多了，试用了一下提些意见。 另外这个图标是不是可以换一换，有点暴力了。
> 
> 题外话：win-tun的clash分支，内网 socks 的 udp 收发貌似有问题。 还有公网访问不了内网设备

关于图标暴力的问题，欢迎提供图标。socks udp无变动

**Comment by yaling888** [comment]
> 还有勾选判断，开启了就关不了。

哪个开关勾了关不了？安装服务后不要删除、移动或改名`SoulService.exe`文件，托盘与服务无关，托盘是否运行都不影响服务的运行，你可以用管理员身份运行cmd，然后单独操作SoulService.exe用于安装或开关服务.
例如：
```shell
SoulService.exe  -service install
SoulService.exe  -service start
SoulService.exe  -service stop
SoulService.exe  -service uninstall
```
安装服务后你还可以用系统命令开关服务：
```shell
net start Soul
net stop Soul
```

**Comment by MetaCubeX** [comment]
大佬你好哈，我是你的小迷弟，关于这个工具，是把SoulX附带的程序创建为服务，通过服务唤起核心吧，我看代码貌似是这么运行的。如果不通过调用唤起，那是不是只有把核心做进计划任务了？

**Comment by MetaCubeX** [comment]
> 还有勾选判断，开启了就关不了。

可能是我核心配置问题，可以忽略。

**Comment by MetaCubeX** [comment]
不过关于s5 upd的问题，应该是内核的s5监听 upd入口寄了

**Comment by yaling888** [comment]
> 大佬你好哈，我是你的小迷弟，关于这个工具，是把SoulX附带的程序创建为服务，通过服务唤起核心吧，我看代码貌似是这么运行的。如果不通过调用唤起，那是不是只有把核心做进计划任务了？

唤起核心是什么？服务是LocalSystem用户在运行，只要核心没有退出或服务没有手动停止，就算注销Windows登录，服务都还在的啊。

**Comment by MetaCubeX** [comment]
> > 大佬你好哈，我是你的小迷弟，关于这个工具，是把SoulX附带的程序创建为服务，通过服务唤起核心吧，我看代码貌似是这么运行的。如果不通过调用唤起，那是不是只有把核心做进计划任务了？
> 
> 唤起核心是什么？服务是LocalSystem用户在运行，只要核心没有退出或服务没有手动停止，就算注销Windows登录，服务都还在的啊。

我的意思是，有没有可能，内核自身把自己注册成服务去运行。
SoulService-windows-amd64

**Comment by yaling888** [comment]
应该可以吧

**Comment by MetaCubeX** [comment]
> 应该可以吧

老大，能要个tg好友位置嘛

**Comment by yaling888** [comment]
> > 应该可以吧
> 
> 老大，能要个tg好友位置嘛

没兴趣
